# Generated by Django 4.1.4 on 2023-08-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtag',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
